services:
  - name: mail-tune
    type: web
    plan: starter
    env: python
    region: oregon  # Choose the region that suits you
    buildCommand: "./build.sh"
    startCommand: "gunicorn mail_tune_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".render.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: mail-tune-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mail-tune-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false  # User will need to input this manually in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # User will need to input this manually in Render dashboard

databases:
  - name: mail-tune-db
    plan: starter
    region: oregon

services:
  - type: redis
    name: mail-tune-redis
    plan: starter
    region: oregon
    ipAllowList: [] # Only allow connections from services in the same account 